### ISSUE TITLE
Issue with reuse-action & go.sum

### ISSUE THREAD

**Issue by fwilhelm92** [fsfe/reuse-action#10]
Hi folks,
thanks for your great work!

We are using the `reuse-action` to lint some golang-files in a ci-workflow. However, we have an issue regarding the `go.sum` file:
- the `reuse-action` fails, if we don't add a copyright header into the `go.sum` file
- the `golangci-lint-action` fails, if we add a copyright header into the `go.sum` file

This issue was already addressed and solved in this PR https://github.com/fsfe/reuse-tool/pull/298, however it seems that it is not yet transferred to the `reuse-action`, if I am not mistaken.

Are there any plans to add these changes into a new release in the near future?

Thanks & kind regards

**Comment by mxmehl** [comment]
True, the PR you've mentioned was merged in mid-January, but the latest REUSE tool release was in December. There are a few issues we would like to resolve before releasing a new tool version though, but it's close to being finished.

Sorry for the wait!

**Comment by fwilhelm92** [comment]
Thanks for the update!
