### ISSUE TITLE
Putting the tool in PATH?

### ISSUE THREAD

**Issue by hoijui** [fsfe/reuse-action#12]
... that's what I would like. :-)
In my github action definition, in a step after  using this action, I run a bash script that internally uses the reuse tool. I run this bash script both on my machine and in CI, to get a reproducible/same/similar testing scenario of my project on my local machine and on CI. For that to work, the `reuse` tool would have to be in the PATH.

Looking on the [base Docker files docu page](https://hub.docker.com/r/fsfe/reuse), I saw that it supposedly is in `~/.local/bin`. Not sure if that `~` refers to the same user as is running the GH action though, or if we would have to use `~reuse/.local/bin` or something, instead.

**Comment by mxmehl** [comment]
Closing as no suitable test case was given.
