### ISSUE TITLE
Support to run on changed files only

### ISSUE THREAD

**Issue by aparcar** [fsfe/reuse-action#13]
Adding this to a large code base is a bit difficult since there are just so many warning. Would it be possible to run the validation on *changed files only*?

**Comment by ewan-escience** [comment]
> However, I am wondering why the current command does not suffice. Even the Linux kernel can be linted in a short timeframe (<1 - ~3 minutes), depending on the machine's power.

For us, it's not about performance, but about semantics. When using this action in a pipeline, we don't want the pipeline to fail when existing files are not compliant, only when _new_ files are not compliant (see e.g. [this issue](https://github.com/research-software-directory/RSD-as-a-service/issues/332)). Is there any chance this will be reconsidered?
