### ISSUE TITLE
New findings although there were no changes to depdendencies nor licenses

### ISSUE THREAD

**Issue by marikaner** [fsfe/reuse-action#16]
Our builds recently started to fail because of the reuse compliance check. I don't really understand why, because we didn't change anything.

We have a node project and all the erroneous files are reported within the `node_modules`. Those are excluded in the `.gitignore`.
According to [this documentation](https://reuse.software/faq/#exclude-file) files referenced in the `.gitignore` should be excluded.

We use a [dep5 file](https://github.com/SAP/cloud-sdk-js/blob/main/.reuse/dep5) for this.

You can find the failing build logs [here](https://github.com/SAP/cloud-sdk-js/runs/6509006680?check_suite_focus=true).

Can you give us some advice whether configuration needs to be changed or whether this is a bug?

**Comment by mxmehl** [comment]
The repository itself is REUSE-compliant. You can also see the REUSE API check via which you have registered the project: https://api.reuse.software/info/github.com/SAP/cloud-sdk-js

The problem in your Github workflow is that a lot of files are added in the file tree before the REUSE check. The node_modules is not present in the repo, so they seem to have been added later.

This itself would not be a problem if Git was available. But the first line in the output reads `reuse.project - WARNING - could not find supported VCS`. That means that the directory in which the check is executed is not a Git repository. Therefore, the .gitignore file cannot be interpreted.

My suggestion: run the REUSE check before any additional files are being added in the workflow.

**Comment by marikaner** [comment]
Thank you, this actually worked 😊
