### ISSUE TITLE
Started failing on existing project: could not find supported VCS

### ISSUE THREAD

**Issue by rpavlik** [fsfe/reuse-action#17]
I've been using this for a while, but recently I've started seeing "reuse.project - WARNING - could not find supported VCS" at the top of my results, then it completely fails to use the gitignore (as you'd expect).  Sample is here: https://github.com/rpavlik/PrettyRegistryXml/runs/7679546043?check_suite_focus=true with commit https://github.com/rpavlik/PrettyRegistryXml/pull/14/commits/142e98771320544f599e2ccd7e0bc23c30399181 (trying to fix it)

if I put the REUSE check before I make any gitignored artifacts, it works once again, but this definitely used to work in the past.

**Comment by mxmehl** [comment]
Indeed, the environment does not seem to be a valid Git repo. I cannot access older action logs to compare, but will investigate.

**Comment by rpavlik** [comment]
thanks!
