### ISSUE TITLE
How to protect the integrity of of this action?

### ISSUE THREAD

**Issue by bernhardreiter** [fsfe/reuse-action#19]
To run this action in sensitive repositories, it is useful to have integrity protection against changes of the action itself, but also of the code of the reuse tool.

In other contexts, this is done by specifying a hash for all components that are used. How can this be done by this action?

(Example: https://w3c.github.io/webappsec-subresource-integrity/#resource-integrity)

**Comment by mxmehl** [comment]
As the action makes use of the `fsfe/reuse` Docker image, one could get the desired image's checksum and clone this.

However, I'd tend to not pin a specific version of the REUSE tool as this would require an update of the action after each new release. We don't have the resources and will to invest a lot of time in this action, especially given that it is only usable on this proprietary platform.

If you wish to pin a specific version, you can do this quite easily yourself in any CI you wish. Just run the REUSE Docker image version of your choice against your repo. See here for some examples: https://reuse.software/dev/#ci (there is no mention of the hash, but that can just be appended).

**Comment by bernhardreiter** [comment]
Thanks for the response.

It would be useful to have an example how to pin the reuse docker image for the various cases (e.g. to replicate this github-action).

**Comment by mxmehl** [comment]
Well, it may depend on your CI how to pin Docker images, but it should usually work to reference the image like this: `fsfe/reuse@sha256:fa93da291f39700a29338b070706f7b4ebe97566650b1cb204bf860f7136ef8e`. This notiation should also work for `docker pull` for example, so it's pretty default and not tied to GitHub actions, REUSE etc.

Note that this is the `latest` tag for amd64.

**Comment by bernhardreiter** [comment]
Thanks!
