### ISSUE TITLE
Action usage licensing question

### ISSUE THREAD

**Issue by aalexanderr** [fsfe/reuse-action#22]
Hi, I'm trying to get Apache-2.0 repository REUSE compliant, the README states that action usage tidbit is
```
# SPDX-License-Identifier: CC0-1.0
```
And it will not be accepted with this license in aforementioned repo. Would the copyright holders be so kind to give blessing to have it Apache-2.0 or should I just write own job using reuse Docker?

**Comment by mxmehl** [comment]
It's OK to re-use this action under Apache-2.0. If you want, you can mention REUSE/Free Software Foundation Europe (FSFE) as author.
