### ISSUE TITLE
How to handle JSON files

### ISSUE THREAD

**Issue by ulucinar** [fsfe/reuse-action#26]
Hi,
We've some JSON files in our repo and running the `reuse-action` fails with the error message `The following files have no copyright and licensing information` for these files. What's the recommended approach for the JSON files?
Thank you!

**Comment by mxmehl** [comment]
The most recommended step is to create accompanying `.license` files: https://reuse.software/tutorial/#binary-and-uncommentable-files

If you have many JSON files in the same directory and want to avoid creating the same amount of .license files, you may want to add a dep5 entry: https://reuse.software/faq/#bulk-license

Note that the DEP5 way is going to be deprecated in favour of a more flexible system in the future, while .license files will stay.

**Comment by ulucinar** [comment]
Thank you @mxmehl for the pointers, very much appreciated.
