### ISSUE TITLE
Should the textual output of the reuse Action go into a GitHub issue?

### ISSUE THREAD

**Issue by jeremiah** [fsfe/reuse-action#5]
Hi,

This GitHub action from reuse is awesome. I wonder the textual output from the Action should go into a GitHub issue. It's not a big deal since you can dig into the Action's output via the GitHub interface but I think that I'd prefer to have the message dumped into an issue, at least when the code is not compliant. This is the output I'm referring to;

```* dist.ini
* docs/_config.yml
* docs/index.html
* t/00-load.t

The following files have no copyright information:
* docs/roadmap.md

The following files have no licensing information:
* README.md
* license_database/GPL-3.0
* spdxl.tx


# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses: CC-BY-4.0, GPL-3.0
* Unused licenses:
* Used licenses:
* Read errors: 0
* Files with copyright information: 5 / 19
* Files with license information: 3 / 19

Unfortunately, your project is not compliant with version 3.0 of the REUSE Specification :-(```

**Comment by mxmehl** [comment]
Interesting idea. However, I would see a few problematic questions:
* For every failed test, would it create a new issue?
* Only for tests in master, or also for every pull request, potentially by others?

Is there any action that does this kind of reporting already? I guess it should be configurable so it doesn't annoy maintainers and contributors.

**Comment by jeremiah** [comment]
> Interesting idea. However, I would see a few problematic questions:
> 
>     * For every failed test, would it create a new issue?

Fair question. I would say no, one issue for everything. (Or you could just put the summary into the issue if the action fails compliance.) Users can always create other issues from the initial issue and spamming them with multiple issue might be icky.

>     * Only for tests in master, or also for every pull request, potentially by others?

The ScanOSS Action does on every pull thought I don't know if it looks at branches. It's my (rather vague) understanding that actions run on every pull regardless of branch or location. This makes actions almost unusable for open source projects and GitHub warns you about this. Frankly I prefer Gitlab's ability to assign a runner with a token and wish GitHub had the same functionality. 
 
> Is there any action that does this kind of reporting already? I guess it should be configurable so it doesn't annoy maintainers and contributors.

The ScanOSS action dumps an issue into issues -> https://github.com/marketplace/scanoss-app 
It has some fatal flaws; 
1. They charge money for more than 5 scans a day
2. It creates really egregious false positives, like: https://github.com/jeremiah/spdxl/issues/20 In that issue they claim my perl module (SPDXL.pm) is copyright IP from StackOverflow. If you surf to SO in the link they provide you'll see that the snippet in question itself has been taken verbatim from the GPL.
